spring:
  ai:
    openai:
      api-key: your-api-key-here
      chat:
        options:
          model: gpt-4o-mini
  datasource:
    url: jdbc:postgresql://8.138.90.155:5432/ai
    username: ai
    password: ai
    driver-class-name: org.postgresql.Driver