# 生产环境配置
server:
  port: 8080

spring:
  # 数据源配置
  datasource:
    url: jdbc:postgresql://${DB_HOST:8.138.90.155}:${DB_PORT:5432}/${DB_NAME:ai}
    username: ${DB_USERNAME:ai}
    password: ${DB_PASSWORD:ai}
    
  # 生产环境JPA配置
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

# 日志配置
logging:
  level:
    cn.iocoder.boot: info
    org.springframework: warn
    org.hibernate: warn
  file:
    name: logs/backend-server.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n' 