server:
  port: 8080

spring:
  application:
    name: backend-server
  
  # 数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://8.138.90.155:5432/ai
    username: ai
    password: ai
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  # MyBatis-Plus配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true  # 下划线转驼峰
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 显示SQL语句
    global-config:
      db-config:
        logic-delete-field: deleted  # 逻辑删除字段名
        logic-delete-value: 1  # 逻辑已删除值
        logic-not-delete-value: 0  # 逻辑未删除值
    
  # Spring AI配置
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

# 日志配置
logging:
  level:
    cn.iocoder.boot: debug
    org.springframework: info
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized 