server:
  port: 8080

spring:
  application:
    name: backend-server
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  
  # 数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatbycard
    username: postgres
    password: postgres
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  # MyBatis-Plus配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true  # 下划线转驼峰
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 显示SQL语句
    global-config:
      db-config:
        logic-delete-field: deleted  # 逻辑删除字段名
        logic-delete-value: 1  # 逻辑已删除值
        logic-not-delete-value: 0  # 逻辑未删除值
  
  # Spring AI配置
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

# 日志配置
logging:
  level:
    cn.iocoder.boot: DEBUG
    org.springframework.web: DEBUG
    org.springframework.ai: DEBUG
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 外部API配置 (已合并，保留内部服务配置)
external:
  chatbycard:
    url: http://localhost:8080

# 跨域配置
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:3001
    - http://0.0.0.0:3001 