# 开发环境配置
server:
  port: 8080

spring:
  # 数据源配置
  datasource:
    url: jdbc:postgresql://8.138.90.155:5432/ai
    username: ai
    password: ai
    
  # 开发时显示SQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# 日志配置
logging:
  level:
    cn.iocoder.boot: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# 外部API配置 - 开发环境
external:
  api:
    workflow:
      url: http://localhost:8000/api/workflows/?skip=0&limit=100
      frontend-url: http://localhost:3001 